### ISSUE TITLE
`spaces create` should check the name of the space is valid

### ISSUE THREAD

**Issue by maksverver** [mathgladiator/adama-lang#108]
I tried creating a space with name `mv-tictactoe` (using the `mv-` prefix to avoid name clashes). But it turns out you can't deploy to a space that contains a hyphen. Trying to do so gives errors like:

```
/Space_mv-tictactoe0.java:22: error: '{' expected
public class Space_mv-tictactoe0 extends LivingDocument {
```

This happens because `-` is not a valid character in a Java class name. It looks like currently only characters that are valid in Java class names are supported. The `spaces create` command should probably do a basic check on the name of the space being created to make sure it contains only valid characters.

**Comment by mathgladiator** [comment]
Thank you for finding that! I've released a new jar which doesn't have this problems. It seems like the CLI was more cavalier than the production path as production was striping non-alphanumeric characters from the generated class name.
