### ISSUE TITLE
Please make libadama.js available over HTTPS

### ISSUE THREAD

**Issue by maksverver** [mathgladiator/adama-lang#109]
Currently, the Adama tutorial recommends including:

```
  <script src="http://releases.adama-platform.com/libadama.js"></script>
```

But this makes it impossible to include libadama.js on pages served over HTTPS on modern browsers. Sadly, it looks like the equivalent HTTPS URL doesn't work today.

Some other things I noticed on the same topic:

  * The Adama handbook *is* available at https://book.adama-platform.com/, but the homepage needlessly links to the HTTP version instead. It might be worth updating these links, or using protocol-relative links (e.g. `<a href="//book.adama-platform.com/">Get started!</a>` would link to the HTTP when the source page is served over HTTP, and HTTPS if the source page is served over HTTPS).
  * The Adama CLI is similarly available at http://releases.adama-platform.com/adama.jar only; it would be very nice to offer this file over HTTPS instead if you expect users to execute it on their machine.

**Comment by mathgladiator** [comment]
Thanks, I will do that when I switch to using github releases for the jar and have the JavaScript hosted by the production endpoint.

I've gone ahead and updated all the links on the website.

**Comment by mathgladiator** [comment]
Jar hosting has been moved from S3 to GitHub: http://book.adama-platform.com/tutorial/00-install.html

**Comment by mathgladiator** [comment]
https://aws-us-east-2.adama-platform.com/libadama.js is the new home to the client and shares the same failure domain as the service. This is now used in https://book.adama-platform.com/tutorial/05-js-client.html and the examples/vanilla-chat
