### ISSUE TITLE
Add a RSS feed for the blog

### ISSUE THREAD

**Issue by gampleman** [mathgladiator/adama-lang#11]
Hi 👋 

I'd like to follow along the blog, but there doesn't seem to be an RSS feed available. Seems like this [can be enabled in docosaurus](https://v2.docusaurus.io/docs/blog#feed), although the documentation implies that it should be on by default?

**Comment by mathgladiator** [comment]
Thanks for the link, that helped. It is enabled with new content published this morning with my thoughts for this month.
http://www.adama-lang.org/blog/rss.xml

**Comment by gampleman** [comment]
I don't think it works properly. Going to http://www.adama-lang.org/blog/rss.xml, the server seems to force a download of an empty file.

**Comment by mathgladiator** [comment]
It would seem that I uploaded a zero byte file... why did docusaurus generate that

**Comment by mathgladiator** [comment]
https://github.com/facebook/docusaurus/issues/2539 seems related, going to update the packages and hope for the best...

a blind update is failing to build, so no easy answer and I have to work through this stuff.

**Comment by mathgladiator** [comment]
OK, I need a simpler option because I pulled forward and got errors, then I pulled back and now I have new errors...

Fortunately, my work is stored in markdown and I just need a simple option to generate the docs and philosophy into an HTML webpage. I have been meaning to focus on this, so either I need to focus on fixing all this docusaurus crap OR find a stable option that does everything I want.

**Comment by mathgladiator** [comment]
ok, I reverted everything, then used the docusaurus tool to regenerate a template and then I just resolved differences manually. Looks like npm update was not ideal, so I picked up some new stuff. Also, I had to convert ids to slugs for blog. I also had a bunch of broken links. All that has been fixed, and the site is now live with www.adama-lang.org/blog/rss.xml having 7.3 kb.

**Comment by gampleman** [comment]
<img width="1205" alt="Screenshot 2021-02-14 at 17 03 41" src="https://user-images.githubusercontent.com/69144/107883387-a255d680-6ee6-11eb-9dae-e5ed30aa6f7e.png">


Seems to be working. Thanks!
