### ISSUE TITLE
implement garbage collection of assets

### ISSUE THREAD

**Issue by mathgladiator** [mathgladiator/adama-lang#121]
Simply put, an asset will always remain available and billed. Fixing this requires scanning the deltas for assets and building up a list of assets to keep.

**Comment by mathgladiator** [comment]
The design process is over, and I've annotated assets with @gc which will allow me to scan an archive to produce a list of assets within the set. This archive can then be used to reconcile against S3.

**Comment by gc** [comment]
> The design process is over, and I've annotated assets with @gc which will allow me to scan an archive to produce a list of assets within the set. This archive can then be used to reconcile against S3.

Sounds good, looking forward to the PR.

**Comment by mathgladiator** [comment]
This is sort-of ready for larger testing, there is now a system to do the stuff.. just need to turn it on and validate it.
