### ISSUE TITLE
CLI command space list shows zero storageBytes

### ISSUE THREAD

**Issue by ziqbal** [mathgladiator/adama-lang#133]
After getting the example chat app working I expected the storagebytes from "space list" to be increasing not stay at 0:

```
space list
{
  "space" : "TOPSECRET",
  "role" : "owner",
  "created" : "2022-11-15",
  "enabled" : true,
  "storageBytes" : 0
}
```

**Comment by mathgladiator** [comment]
It takes about an hour for the storage bytes to compute as it hooks into the billing mechanism.
