### ISSUE TITLE
Consider a PostgreSQL option?

### ISSUE THREAD

**Issue by KnowledgeGarden** [mathgladiator/adama-lang#158]
Just asking...are there arguments against a psql driver?

**Comment by mathgladiator** [comment]
No real arguments against, just went with what I could setup easily in my basement. I haven't tested at all with PostgreSQL

**Comment by KnowledgeGarden** [comment]
Thanks. That's good news. It does appear that the core platform is not dependent on mysql; where it is may not apply if the focus is on core functions.
